# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    tags:
      - xPrintTalkLib-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Check out sources...
      uses: actions/checkout@v2

    - name: Debug
      run: echo ${GITHUB_REF##*-}

    - name: Decrypt GGP Ring File
      env:
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: gpg --quiet --batch --yes --decrypt --passphrase="$SIGNING_PASSWORD" --output secring.gpg secring.gpg.gpg && chmod +x secring.gpg

    - name: Build and Release to Maven Central Repository
      env:
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: ./gradlew uploadArchives closeAndReleaseRepository -PprojectVersion=${GITHUB_REF##*-} -Psigning.keyId=$SIGNING_KEY_ID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=$PWD/secring.gpg -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD

    - name: Attach files to GitHub Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/libs/*'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

